### ISSUE TITLE
权重咨询

### ISSUE THREAD

**Issue by haozhang09** [zhangjiancheng2000/RCUMP-TIP#1]
请问能提供训练好的权重文件么？

**Comment by ZhangJC-2k** [comment]
可以的，我明天整理下

**Comment by ZhangJC-2k** [comment]
权重可以在[这里](链接：https://pan.baidu.com/s/1RDkPTAPq8s3_W4SEDi3S0g?pwd=v2gw)下载

**Comment by ZhangJC-2k** [comment]
一个暂时的9阶段权重能在[https://pan.baidu.com/s/1RDkPTAPq8s3_W4SEDi3S0g?pwd=v2gw ]下载。因为释放的代码经过优化跟原来的有些差别，先前的权重没法直接载入，更多权重将会在重新训练之后提供。
